#!/bin/bash
./configure \
	--prefix=/usr \
	--libdir=/usr/lib${LIBDIRSUFFIX} \
	--disable-static \
	--program-prefix= \
	--program-suffix= \
	--build=$ARCH-slackware-linux \
	--with-png \
	--with-freetype \
	--without-x \
|| exit 1
