#!/bin/bash
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --mandir=/usr/man \
  --docdir=/usr/doc/pango-$VERSION \
  --build=$ARCH-slackware-linux \
  --host=$ARCH-slackware-linux \
  --target=$ARCH-slackware-linux \
  --without-x \
  --enable-shared \
|| exit 1
